-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: May 23, 2020 at 02:02 PM
-- Server version: 5.7.26
-- PHP Version: 7.3.8

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `myfrag`
--

-- --------------------------------------------------------

--
-- Table structure for table `notes_categories`
--

CREATE TABLE `notes_categories` (
  `id` int(11) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `description` text,
  `active_status` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `notes_categories`
--

INSERT INTO `notes_categories` (`id`, `name`, `image`, `description`, `active_status`, `created_at`, `updated_at`, `created_by`, `updated_by`) VALUES
(1, 'CITRUS SMELLS', 'uploads/notes_categories/1.jpeg', 'Fruity notes beyond citrus (which form a class of its own) have become so popular in recent years that they deserve a category of their own. Vegetable notes are more unusual, sometimes rendered through illusion: an example would be the turnip note that iris rhizome sometimes produces.\r\n\r\nAs a rule fruits and vegetables are resistant to distillation and extraction processes due to the very high percentage of water in their natural make-up, and they remain a reconstructed note in fragrances. Their effect ranges from the refreshing to the succulent, all the way to the musty and mysterious.\r\n\r\nFruits and vegetables provide a nuanced texture and a refreshing feel in fragrances. Fruits especially have been extremely popular in the floral fruity category in the 2000s, while peach and plum have been major components in classical perfumers\' \"bases\" (such as the famous Persicol) which produced many of the iconic fragrances of the first half of the 20th century.', 1, NULL, NULL, 1, 1),
(2, 'FRUITS, VEGETABLES AND NUTS ', 'uploads/notes_categories/2.jpeg', 'Fruity notes beyond citrus (which form a class of its own) have become so popular in recent years that they deserve a category of their own. Vegetable notes are more unusual, sometimes rendered through illusion: an example would be the turnip note that iris rhizome sometimes produces.\r\n\r\nAs a rule fruits and vegetables are resistant to distillation and extraction processes due to the very high percentage of water in their natural make-up, and they remain a reconstructed note in fragrances. Their effect ranges from the refreshing to the succulent, all the way to the musty and mysterious.\r\n\r\nFruits and vegetables provide a nuanced texture and a refreshing feel in fragrances. Fruits especially have been extremely popular in the floral fruity category in the 2000s, while peach and plum have been major components in classical perfumers\' \"bases\" (such as the famous Persicol) which produced many of the iconic fragrances of the first half of the 20th century.', 1, NULL, NULL, NULL, NULL),
(3, 'FLOWERS', 'uploads/notes_categories/3.jpeg', 'Fruity notes beyond citrus (which form a class of its own) have become so popular in recent years that they deserve a category of their own. Vegetable notes are more unusual, sometimes rendered through illusion: an example would be the turnip note that iris rhizome sometimes produces.\r\n\r\nAs a rule fruits and vegetables are resistant to distillation and extraction processes due to the very high percentage of water in their natural make-up, and they remain a reconstructed note in fragrances. Their effect ranges from the refreshing to the succulent, all the way to the musty and mysterious.\r\n\r\nFruits and vegetables provide a nuanced texture and a refreshing feel in fragrances. Fruits especially have been extremely popular in the floral fruity category in the 2000s, while peach and plum have been major components in classical perfumers\' \"bases\" (such as the famous Persicol) which produced many of the iconic fragrances of the first half of the 20th century.', 1, NULL, NULL, NULL, NULL),
(4, 'WHITE FLOWERS', 'uploads/notes_categories/4.jpeg', 'Fruity notes beyond citrus (which form a class of its own) have become so popular in recent years that they deserve a category of their own. Vegetable notes are more unusual, sometimes rendered through illusion: an example would be the turnip note that iris rhizome sometimes produces.\r\n\r\nAs a rule fruits and vegetables are resistant to distillation and extraction processes due to the very high percentage of water in their natural make-up, and they remain a reconstructed note in fragrances. Their effect ranges from the refreshing to the succulent, all the way to the musty and mysterious.\r\n\r\nFruits and vegetables provide a nuanced texture and a refreshing feel in fragrances. Fruits especially have been extremely popular in the floral fruity category in the 2000s, while peach and plum have been major components in classical perfumers\' \"bases\" (such as the famous Persicol) which produced many of the iconic fragrances of the first half of the 20th century.', 1, NULL, NULL, NULL, NULL),
(5, 'GREENS', 'uploads/notes_categories/5.jpeg', 'Fruity notes beyond citrus (which form a class of its own) have become so popular in recent years that they deserve a category of their own. Vegetable notes are more unusual, sometimes rendered through illusion: an example would be the turnip note that iris rhizome sometimes produces.\r\n\r\nAs a rule fruits and vegetables are resistant to distillation and extraction processes due to the very high percentage of water in their natural make-up, and they remain a reconstructed note in fragrances. Their effect ranges from the refreshing to the succulent, all the way to the musty and mysterious.\r\n\r\nFruits and vegetables provide a nuanced texture and a refreshing feel in fragrances. Fruits especially have been extremely popular in the floral fruity category in the 2000s, while peach and plum have been major components in classical perfumers\' \"bases\" (such as the famous Persicol) which produced many of the iconic fragrances of the first half of the 20th century.', 1, NULL, NULL, NULL, NULL),
(6, 'HERBS AND FOUGERES', 'uploads/notes_categories/6.jpeg', 'Fruity notes beyond citrus (which form a class of its own) have become so popular in recent years that they deserve a category of their own. Vegetable notes are more unusual, sometimes rendered through illusion: an example would be the turnip note that iris rhizome sometimes produces.\r\n\r\nAs a rule fruits and vegetables are resistant to distillation and extraction processes due to the very high percentage of water in their natural make-up, and they remain a reconstructed note in fragrances. Their effect ranges from the refreshing to the succulent, all the way to the musty and mysterious.\r\n\r\nFruits and vegetables provide a nuanced texture and a refreshing feel in fragrances. Fruits especially have been extremely popular in the floral fruity category in the 2000s, while peach and plum have been major components in classical perfumers\' \"bases\" (such as the famous Persicol) which produced many of the iconic fragrances of the first half of the 20th century.', 1, NULL, NULL, NULL, NULL),
(7, 'SPICES', 'uploads/notes_categories/7.jpeg', 'Fruity notes beyond citrus (which form a class of its own) have become so popular in recent years that they deserve a category of their own. Vegetable notes are more unusual, sometimes rendered through illusion: an example would be the turnip note that iris rhizome sometimes produces.\r\n\r\nAs a rule fruits and vegetables are resistant to distillation and extraction processes due to the very high percentage of water in their natural make-up, and they remain a reconstructed note in fragrances. Their effect ranges from the refreshing to the succulent, all the way to the musty and mysterious.\r\n\r\nFruits and vegetables provide a nuanced texture and a refreshing feel in fragrances. Fruits especially have been extremely popular in the floral fruity category in the 2000s, while peach and plum have been major components in classical perfumers\' \"bases\" (such as the famous Persicol) which produced many of the iconic fragrances of the first half of the 20th century.', 1, NULL, NULL, NULL, NULL),
(8, 'SWEETS AND GOURMAND SMELLS', 'uploads/notes_categories/8.jpeg', 'Fruity notes beyond citrus (which form a class of its own) have become so popular in recent years that they deserve a category of their own. Vegetable notes are more unusual, sometimes rendered through illusion: an example would be the turnip note that iris rhizome sometimes produces.\r\n\r\nAs a rule fruits and vegetables are resistant to distillation and extraction processes due to the very high percentage of water in their natural make-up, and they remain a reconstructed note in fragrances. Their effect ranges from the refreshing to the succulent, all the way to the musty and mysterious.\r\n\r\nFruits and vegetables provide a nuanced texture and a refreshing feel in fragrances. Fruits especially have been extremely popular in the floral fruity category in the 2000s, while peach and plum have been major components in classical perfumers\' \"bases\" (such as the famous Persicol) which produced many of the iconic fragrances of the first half of the 20th century.', 1, NULL, NULL, NULL, NULL),
(9, 'WOODS AND MOSSES', 'uploads/notes_categories/1.jpeg', 'Fruity notes beyond citrus (which form a class of its own) have become so popular in recent years that they deserve a category of their own. Vegetable notes are more unusual, sometimes rendered through illusion: an example would be the turnip note that iris rhizome sometimes produces.\r\n\r\nAs a rule fruits and vegetables are resistant to distillation and extraction processes due to the very high percentage of water in their natural make-up, and they remain a reconstructed note in fragrances. Their effect ranges from the refreshing to the succulent, all the way to the musty and mysterious.\r\n\r\nFruits and vegetables provide a nuanced texture and a refreshing feel in fragrances. Fruits especially have been extremely popular in the floral fruity category in the 2000s, while peach and plum have been major components in classical perfumers\' \"bases\" (such as the famous Persicol) which produced many of the iconic fragrances of the first half of the 20th century.', 1, NULL, NULL, NULL, NULL),
(10, 'RESINS AND BALSAMS', 'uploads/notes_categories/2.jpeg', 'Fruity notes beyond citrus (which form a class of its own) have become so popular in recent years that they deserve a category of their own. Vegetable notes are more unusual, sometimes rendered through illusion: an example would be the turnip note that iris rhizome sometimes produces.\r\n\r\nAs a rule fruits and vegetables are resistant to distillation and extraction processes due to the very high percentage of water in their natural make-up, and they remain a reconstructed note in fragrances. Their effect ranges from the refreshing to the succulent, all the way to the musty and mysterious.\r\n\r\nFruits and vegetables provide a nuanced texture and a refreshing feel in fragrances. Fruits especially have been extremely popular in the floral fruity category in the 2000s, while peach and plum have been major components in classical perfumers\' \"bases\" (such as the famous Persicol) which produced many of the iconic fragrances of the first half of the 20th century.', 1, NULL, NULL, NULL, NULL),
(11, 'MUSK', 'uploads/notes_categories/3.jpeg', 'Fruity notes beyond citrus (which form a class of its own) have become so popular in recent years that they deserve a category of their own. Vegetable notes are more unusual, sometimes rendered through illusion: an example would be the turnip note that iris rhizome sometimes produces.\r\n\r\nAs a rule fruits and vegetables are resistant to distillation and extraction processes due to the very high percentage of water in their natural make-up, and they remain a reconstructed note in fragrances. Their effect ranges from the refreshing to the succulent, all the way to the musty and mysterious.\r\n\r\nFruits and vegetables provide a nuanced texture and a refreshing feel in fragrances. Fruits especially have been extremely popular in the floral fruity category in the 2000s, while peach and plum have been major components in classical perfumers\' \"bases\" (such as the famous Persicol) which produced many of the iconic fragrances of the first half of the 20th century.', 1, NULL, NULL, NULL, NULL),
(12, 'AMBER', 'uploads/notes_categories/4.jpeg', 'Fruity notes beyond citrus (which form a class of its own) have become so popular in recent years that they deserve a category of their own. Vegetable notes are more unusual, sometimes rendered through illusion: an example would be the turnip note that iris rhizome sometimes produces.\r\n\r\nAs a rule fruits and vegetables are resistant to distillation and extraction processes due to the very high percentage of water in their natural make-up, and they remain a reconstructed note in fragrances. Their effect ranges from the refreshing to the succulent, all the way to the musty and mysterious.\r\n\r\nFruits and vegetables provide a nuanced texture and a refreshing feel in fragrances. Fruits especially have been extremely popular in the floral fruity category in the 2000s, while peach and plum have been major components in classical perfumers\' \"bases\" (such as the famous Persicol) which produced many of the iconic fragrances of the first half of the 20th century.', 1, NULL, NULL, NULL, NULL),
(13, 'ANIMALIC SMELLS', 'uploads/notes_categories/5.jpeg', 'Fruity notes beyond citrus (which form a class of its own) have become so popular in recent years that they deserve a category of their own. Vegetable notes are more unusual, sometimes rendered through illusion: an example would be the turnip note that iris rhizome sometimes produces.\r\n\r\nAs a rule fruits and vegetables are resistant to distillation and extraction processes due to the very high percentage of water in their natural make-up, and they remain a reconstructed note in fragrances. Their effect ranges from the refreshing to the succulent, all the way to the musty and mysterious.\r\n\r\nFruits and vegetables provide a nuanced texture and a refreshing feel in fragrances. Fruits especially have been extremely popular in the floral fruity category in the 2000s, while peach and plum have been major components in classical perfumers\' \"bases\" (such as the famous Persicol) which produced many of the iconic fragrances of the first half of the 20th century.', 1, NULL, NULL, NULL, NULL),
(14, 'BEVERAGES', 'uploads/notes_categories/6.jpeg', 'Fruity notes beyond citrus (which form a class of its own) have become so popular in recent years that they deserve a category of their own. Vegetable notes are more unusual, sometimes rendered through illusion: an example would be the turnip note that iris rhizome sometimes produces.\r\n\r\nAs a rule fruits and vegetables are resistant to distillation and extraction processes due to the very high percentage of water in their natural make-up, and they remain a reconstructed note in fragrances. Their effect ranges from the refreshing to the succulent, all the way to the musty and mysterious.\r\n\r\nFruits and vegetables provide a nuanced texture and a refreshing feel in fragrances. Fruits especially have been extremely popular in the floral fruity category in the 2000s, while peach and plum have been major components in classical perfumers\' \"bases\" (such as the famous Persicol) which produced many of the iconic fragrances of the first half of the 20th century.', 1, NULL, NULL, NULL, NULL),
(15, 'NATURAL AND SYNTHETIC', 'uploads/notes_categories/7.jpeg', 'Fruity notes beyond citrus (which form a class of its own) have become so popular in recent years that they deserve a category of their own. Vegetable notes are more unusual, sometimes rendered through illusion: an example would be the turnip note that iris rhizome sometimes produces.\r\n\r\nAs a rule fruits and vegetables are resistant to distillation and extraction processes due to the very high percentage of water in their natural make-up, and they remain a reconstructed note in fragrances. Their effect ranges from the refreshing to the succulent, all the way to the musty and mysterious.\r\n\r\nFruits and vegetables provide a nuanced texture and a refreshing feel in fragrances. Fruits especially have been extremely popular in the floral fruity category in the 2000s, while peach and plum have been major components in classical perfumers\' \"bases\" (such as the famous Persicol) which produced many of the iconic fragrances of the first half of the 20th century.', 1, NULL, NULL, NULL, NULL),
(16, 'POPULAR AND WEIRD', 'uploads/notes_categories/8.jpeg', 'Fruity notes beyond citrus (which form a class of its own) have become so popular in recent years that they deserve a category of their own. Vegetable notes are more unusual, sometimes rendered through illusion: an example would be the turnip note that iris rhizome sometimes produces.\r\n\r\nAs a rule fruits and vegetables are resistant to distillation and extraction processes due to the very high percentage of water in their natural make-up, and they remain a reconstructed note in fragrances. Their effect ranges from the refreshing to the succulent, all the way to the musty and mysterious.\r\n\r\nFruits and vegetables provide a nuanced texture and a refreshing feel in fragrances. Fruits especially have been extremely popular in the floral fruity category in the 2000s, while peach and plum have been major components in classical perfumers\' \"bases\" (such as the famous Persicol) which produced many of the iconic fragrances of the first half of the 20th century.', 1, NULL, NULL, NULL, NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `notes_categories`
--
ALTER TABLE `notes_categories`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `notes_categories`
--
ALTER TABLE `notes_categories`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
